/*
 * Credits
 * The Credits API provides information about customer credit lines.
 *
 * OpenAPI spec version: 2.2.0
 * Contact: gipinacho@santander.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.CardDetail;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;
/**
 * BenefitDetail
 */

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-04-11T10:52:34.405704-05:00[America/Bogota]")
public class BenefitDetail {
  @SerializedName("hiring_date")
  private OffsetDateTime hiringDate = null;

  @SerializedName("contract_key")
  private String contractKey = null;

  @SerializedName("activation_date")
  private OffsetDateTime activationDate = null;

  @SerializedName("type")
  private String type = null;

  /**
   * Indicates the status of the benefit.   * &#x60;INITIAL&#x60; -  Indicates the start of benefit.   * &#x60;EVALUATION&#x60; - Indicates when the benefit is in Evaluation.   * &#x60;FINAL&#x60; - Indicates the final phase of benefit. 
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    INITIAL("INITIAL"),
    EVALUATION("EVALUATION"),
    FINAL("FINAL");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static StatusEnum fromValue(String input) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return StatusEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("status")
  private StatusEnum status = null;

  @SerializedName("last_evaluation_date")
  private OffsetDateTime lastEvaluationDate = null;

  @SerializedName("cut_of_date")
  private OffsetDateTime cutOfDate = null;

  @SerializedName("card")
  private CardDetail card = null;

  public BenefitDetail hiringDate(OffsetDateTime hiringDate) {
    this.hiringDate = hiringDate;
    return this;
  }

   /**
   * This date specifies the date of contracting the benefit. [ISO 8601] (https://www.iso.org/iso-8601-date-and-time-format.html
   * @return hiringDate
  **/
  @Schema(example = "2022-03-16T23:38:45.408Z", description = "This date specifies the date of contracting the benefit. [ISO 8601] (https://www.iso.org/iso-8601-date-and-time-format.html")
  public OffsetDateTime getHiringDate() {
    return hiringDate;
  }

  public void setHiringDate(OffsetDateTime hiringDate) {
    this.hiringDate = hiringDate;
  }

  public BenefitDetail contractKey(String contractKey) {
    this.contractKey = contractKey;
    return this;
  }

   /**
   * Indicates the key contract for the benefit
   * @return contractKey
  **/
  @Schema(example = "213131315446", description = "Indicates the key contract for the benefit")
  public String getContractKey() {
    return contractKey;
  }

  public void setContractKey(String contractKey) {
    this.contractKey = contractKey;
  }

  public BenefitDetail activationDate(OffsetDateTime activationDate) {
    this.activationDate = activationDate;
    return this;
  }

   /**
   * This date specifies the date of activation of the benefit. [ISO 8601] (https://www.iso.org/iso-8601-date-and-time-format.html
   * @return activationDate
  **/
  @Schema(example = "2022-03-16T23:38:45.408Z", description = "This date specifies the date of activation of the benefit. [ISO 8601] (https://www.iso.org/iso-8601-date-and-time-format.html")
  public OffsetDateTime getActivationDate() {
    return activationDate;
  }

  public void setActivationDate(OffsetDateTime activationDate) {
    this.activationDate = activationDate;
  }

  public BenefitDetail type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Indicates the benefit type
   * @return type
  **/
  @Schema(example = "GM_2", description = "Indicates the benefit type")
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public BenefitDetail status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Indicates the status of the benefit.   * &#x60;INITIAL&#x60; -  Indicates the start of benefit.   * &#x60;EVALUATION&#x60; - Indicates when the benefit is in Evaluation.   * &#x60;FINAL&#x60; - Indicates the final phase of benefit. 
   * @return status
  **/
  @Schema(description = "Indicates the status of the benefit.   * `INITIAL` -  Indicates the start of benefit.   * `EVALUATION` - Indicates when the benefit is in Evaluation.   * `FINAL` - Indicates the final phase of benefit. ")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public BenefitDetail lastEvaluationDate(OffsetDateTime lastEvaluationDate) {
    this.lastEvaluationDate = lastEvaluationDate;
    return this;
  }

   /**
   * Indicates the last evaluation date for the benefit.[ISO 8601] (https://www.iso.org/iso-8601-date-and-time-format.html
   * @return lastEvaluationDate
  **/
  @Schema(example = "2022-03-16T23:38:45.408Z", description = "Indicates the last evaluation date for the benefit.[ISO 8601] (https://www.iso.org/iso-8601-date-and-time-format.html")
  public OffsetDateTime getLastEvaluationDate() {
    return lastEvaluationDate;
  }

  public void setLastEvaluationDate(OffsetDateTime lastEvaluationDate) {
    this.lastEvaluationDate = lastEvaluationDate;
  }

  public BenefitDetail cutOfDate(OffsetDateTime cutOfDate) {
    this.cutOfDate = cutOfDate;
    return this;
  }

   /**
   * This date specifies the date of finish of the benefit. [ISO 8601] (https://www.iso.org/iso-8601-date-and-time-format.html
   * @return cutOfDate
  **/
  @Schema(example = "2022-03-16T23:38:45.408Z", description = "This date specifies the date of finish of the benefit. [ISO 8601] (https://www.iso.org/iso-8601-date-and-time-format.html")
  public OffsetDateTime getCutOfDate() {
    return cutOfDate;
  }

  public void setCutOfDate(OffsetDateTime cutOfDate) {
    this.cutOfDate = cutOfDate;
  }

  public BenefitDetail card(CardDetail card) {
    this.card = card;
    return this;
  }

   /**
   * Get card
   * @return card
  **/
  @Schema(description = "")
  public CardDetail getCard() {
    return card;
  }

  public void setCard(CardDetail card) {
    this.card = card;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BenefitDetail benefitDetail = (BenefitDetail) o;
    return Objects.equals(this.hiringDate, benefitDetail.hiringDate) &&
        Objects.equals(this.contractKey, benefitDetail.contractKey) &&
        Objects.equals(this.activationDate, benefitDetail.activationDate) &&
        Objects.equals(this.type, benefitDetail.type) &&
        Objects.equals(this.status, benefitDetail.status) &&
        Objects.equals(this.lastEvaluationDate, benefitDetail.lastEvaluationDate) &&
        Objects.equals(this.cutOfDate, benefitDetail.cutOfDate) &&
        Objects.equals(this.card, benefitDetail.card);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hiringDate, contractKey, activationDate, type, status, lastEvaluationDate, cutOfDate, card);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BenefitDetail {\n");
    
    sb.append("    hiringDate: ").append(toIndentedString(hiringDate)).append("\n");
    sb.append("    contractKey: ").append(toIndentedString(contractKey)).append("\n");
    sb.append("    activationDate: ").append(toIndentedString(activationDate)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    lastEvaluationDate: ").append(toIndentedString(lastEvaluationDate)).append("\n");
    sb.append("    cutOfDate: ").append(toIndentedString(cutOfDate)).append("\n");
    sb.append("    card: ").append(toIndentedString(card)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
