/*
 * Credits
 * The Credits API provides information about customer credit lines.
 *
 * OpenAPI spec version: 2.2.0
 * Contact: gipinacho@santander.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
/**
 * Cursors object for identifying pagination before and after
 */
@Schema(description = "Cursors object for identifying pagination before and after")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-04-11T10:52:34.405704-05:00[America/Bogota]")
public class Cursor {
  @SerializedName("next_cursor_key")
  private String nextCursorKey = null;

  public Cursor nextCursorKey(String nextCursorKey) {
    this.nextCursorKey = nextCursorKey;
    return this;
  }

   /**
   * The next cursor key for the set of entries retrieved. This value is left absent when there are no more values to return
   * @return nextCursorKey
  **/
  @Schema(example = "10", description = "The next cursor key for the set of entries retrieved. This value is left absent when there are no more values to return")
  public String getNextCursorKey() {
    return nextCursorKey;
  }

  public void setNextCursorKey(String nextCursorKey) {
    this.nextCursorKey = nextCursorKey;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Cursor cursor = (Cursor) o;
    return Objects.equals(this.nextCursorKey, cursor.nextCursorKey);
  }

  @Override
  public int hashCode() {
    return Objects.hash(nextCursorKey);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Cursor {\n");
    
    sb.append("    nextCursorKey: ").append(toIndentedString(nextCursorKey)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
