/*
 * Credits
 * The Credits API provides information about customer credit lines.
 *
 * OpenAPI spec version: 2.2.0
 * Contact: gipinacho@santander.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import org.threeten.bp.OffsetDateTime;
/**
 * Retrieves the use of digital channels for this period
 */
@Schema(description = "Retrieves the use of digital channels for this period")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-04-11T10:52:34.405704-05:00[America/Bogota]")
public class DigitalChannelDetail {
  @SerializedName("id")
  private String id = null;

  /**
   * Indicates if customer has used digital channels in the period   * &#x60;ACTIVE&#x60; -  Indicates that the customer has used digital channels in this period.   * &#x60;INACTIVE&#x60; - Indicates that the customer has not used digital channels in this period. 
   */
  @JsonAdapter(StatusEnum.Adapter.class)
  public enum StatusEnum {
    ACTIVE("ACTIVE"),
    INACTIVE("INACTIVE");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }
    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }
    public static StatusEnum fromValue(String input) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(input)) {
          return b;
        }
      }
      return null;
    }
    public static class Adapter extends TypeAdapter<StatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final StatusEnum enumeration) throws IOException {
        jsonWriter.value(String.valueOf(enumeration.getValue()));
      }

      @Override
      public StatusEnum read(final JsonReader jsonReader) throws IOException {
        Object value = jsonReader.nextString();
        return StatusEnum.fromValue((String)(value));
      }
    }
  }  @SerializedName("status")
  private StatusEnum status = null;

  @SerializedName("operation_date")
  private OffsetDateTime operationDate = null;

  public DigitalChannelDetail id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Indicates tuse of digital channels identifier.
   * @return id
  **/
  @Schema(example = "01", description = "Indicates tuse of digital channels identifier.")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public DigitalChannelDetail status(StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Indicates if customer has used digital channels in the period   * &#x60;ACTIVE&#x60; -  Indicates that the customer has used digital channels in this period.   * &#x60;INACTIVE&#x60; - Indicates that the customer has not used digital channels in this period. 
   * @return status
  **/
  @Schema(description = "Indicates if customer has used digital channels in the period   * `ACTIVE` -  Indicates that the customer has used digital channels in this period.   * `INACTIVE` - Indicates that the customer has not used digital channels in this period. ")
  public StatusEnum getStatus() {
    return status;
  }

  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public DigitalChannelDetail operationDate(OffsetDateTime operationDate) {
    this.operationDate = operationDate;
    return this;
  }

   /**
   * Indicates the date when this information was collected. [ISO 8601] (https://www.iso.org/iso-8601-date-and-time-format.html
   * @return operationDate
  **/
  @Schema(example = "2012-02-16T23:38:45.408Z", description = "Indicates the date when this information was collected. [ISO 8601] (https://www.iso.org/iso-8601-date-and-time-format.html")
  public OffsetDateTime getOperationDate() {
    return operationDate;
  }

  public void setOperationDate(OffsetDateTime operationDate) {
    this.operationDate = operationDate;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DigitalChannelDetail digitalChannelDetail = (DigitalChannelDetail) o;
    return Objects.equals(this.id, digitalChannelDetail.id) &&
        Objects.equals(this.status, digitalChannelDetail.status) &&
        Objects.equals(this.operationDate, digitalChannelDetail.operationDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, status, operationDate);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DigitalChannelDetail {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    operationDate: ").append(toIndentedString(operationDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
