/*
 * Credits
 * The Credits API provides information about customer credit lines.
 *
 * OpenAPI spec version: 2.2.0
 * Contact: gipinacho@santander.com.mx
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.client.model.OperationReferences;
import io.swagger.v3.oas.annotations.media.Schema;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.threeten.bp.OffsetDateTime;
/**
 * Contains the information of a transaction made by the customer
 */
@Schema(description = "Contains the information of a transaction made by the customer")
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaClientCodegen", date = "2022-04-11T10:52:34.405704-05:00[America/Bogota]")
public class TransactionDetail {
  @SerializedName("key")
  private String key = null;

  @SerializedName("transaction_origin")
  private String transactionOrigin = null;

  @SerializedName("creation_date")
  private OffsetDateTime creationDate = null;

  @SerializedName("posted_date")
  private OffsetDateTime postedDate = null;

  @SerializedName("balance")
  private AllOfTransactionDetailBalance balance = null;

  @SerializedName("card_number")
  private String cardNumber = null;

  @SerializedName("description")
  private String description = null;

  @SerializedName("references")
  private List<OperationReferences> references = null;

  @SerializedName("award_points_info")
  private AllOfTransactionDetailAwardPointsInfo awardPointsInfo = null;

  public TransactionDetail key(String key) {
    this.key = key;
    return this;
  }

   /**
   * The transaction unique identifier.
   * @return key
  **/
  @Schema(example = "4e20fbb243684d9eb19ff33a50ee422e", description = "The transaction unique identifier.")
  public String getKey() {
    return key;
  }

  public void setKey(String key) {
    this.key = key;
  }

  public TransactionDetail transactionOrigin(String transactionOrigin) {
    this.transactionOrigin = transactionOrigin;
    return this;
  }

   /**
   * Origin  of the transaction, could be the business name where the transaction was made.
   * @return transactionOrigin
  **/
  @Schema(example = "Sanborns", description = "Origin  of the transaction, could be the business name where the transaction was made.")
  public String getTransactionOrigin() {
    return transactionOrigin;
  }

  public void setTransactionOrigin(String transactionOrigin) {
    this.transactionOrigin = transactionOrigin;
  }

  public TransactionDetail creationDate(OffsetDateTime creationDate) {
    this.creationDate = creationDate;
    return this;
  }

   /**
   * Date when the transfer was made by the customer.  [ISO 8601] (https://www.iso.org/iso-8601-date-and-time-format.html).
   * @return creationDate
  **/
  @Schema(example = "2017-02-03T17:32:28Z", description = "Date when the transfer was made by the customer.  [ISO 8601] (https://www.iso.org/iso-8601-date-and-time-format.html).")
  public OffsetDateTime getCreationDate() {
    return creationDate;
  }

  public void setCreationDate(OffsetDateTime creationDate) {
    this.creationDate = creationDate;
  }

  public TransactionDetail postedDate(OffsetDateTime postedDate) {
    this.postedDate = postedDate;
    return this;
  }

   /**
   * Date when the transfer was posted. [ISO 8601] (https://www.iso.org/iso-8601-date-and-time-format.html).
   * @return postedDate
  **/
  @Schema(example = "2017-02-05T17:32:28Z", description = "Date when the transfer was posted. [ISO 8601] (https://www.iso.org/iso-8601-date-and-time-format.html).")
  public OffsetDateTime getPostedDate() {
    return postedDate;
  }

  public void setPostedDate(OffsetDateTime postedDate) {
    this.postedDate = postedDate;
  }

  public TransactionDetail balance(AllOfTransactionDetailBalance balance) {
    this.balance = balance;
    return this;
  }

   /**
   * Retrieved the amount of the transaction. Expense or income symbol (+ in green / - in red).
   * @return balance
  **/
  @Schema(description = "Retrieved the amount of the transaction. Expense or income symbol (+ in green / - in red).")
  public AllOfTransactionDetailBalance getBalance() {
    return balance;
  }

  public void setBalance(AllOfTransactionDetailBalance balance) {
    this.balance = balance;
  }

  public TransactionDetail cardNumber(String cardNumber) {
    this.cardNumber = cardNumber;
    return this;
  }

   /**
   * This card number belongs to the card which was used in the banking operation.
   * @return cardNumber
  **/
  @Schema(example = "9943 1234 5678 9012", description = "This card number belongs to the card which was used in the banking operation.")
  public String getCardNumber() {
    return cardNumber;
  }

  public void setCardNumber(String cardNumber) {
    this.cardNumber = cardNumber;
  }

  public TransactionDetail description(String description) {
    this.description = description;
    return this;
  }

   /**
   * Detail of the transaction. Could indicate the reason of the transaction.
   * @return description
  **/
  @Schema(example = "Consumo Amazon MX", description = "Detail of the transaction. Could indicate the reason of the transaction.")
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public TransactionDetail references(List<OperationReferences> references) {
    this.references = references;
    return this;
  }

  public TransactionDetail addReferencesItem(OperationReferences referencesItem) {
    if (this.references == null) {
      this.references = new ArrayList<OperationReferences>();
    }
    this.references.add(referencesItem);
    return this;
  }

   /**
   * Get references
   * @return references
  **/
  @Schema(description = "")
  public List<OperationReferences> getReferences() {
    return references;
  }

  public void setReferences(List<OperationReferences> references) {
    this.references = references;
  }

  public TransactionDetail awardPointsInfo(AllOfTransactionDetailAwardPointsInfo awardPointsInfo) {
    this.awardPointsInfo = awardPointsInfo;
    return this;
  }

   /**
   * The necessary information of the award points for paying the selected transaction.
   * @return awardPointsInfo
  **/
  @Schema(description = "The necessary information of the award points for paying the selected transaction.")
  public AllOfTransactionDetailAwardPointsInfo getAwardPointsInfo() {
    return awardPointsInfo;
  }

  public void setAwardPointsInfo(AllOfTransactionDetailAwardPointsInfo awardPointsInfo) {
    this.awardPointsInfo = awardPointsInfo;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TransactionDetail transactionDetail = (TransactionDetail) o;
    return Objects.equals(this.key, transactionDetail.key) &&
        Objects.equals(this.transactionOrigin, transactionDetail.transactionOrigin) &&
        Objects.equals(this.creationDate, transactionDetail.creationDate) &&
        Objects.equals(this.postedDate, transactionDetail.postedDate) &&
        Objects.equals(this.balance, transactionDetail.balance) &&
        Objects.equals(this.cardNumber, transactionDetail.cardNumber) &&
        Objects.equals(this.description, transactionDetail.description) &&
        Objects.equals(this.references, transactionDetail.references) &&
        Objects.equals(this.awardPointsInfo, transactionDetail.awardPointsInfo);
  }

  @Override
  public int hashCode() {
    return Objects.hash(key, transactionOrigin, creationDate, postedDate, balance, cardNumber, description, references, awardPointsInfo);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransactionDetail {\n");
    
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    transactionOrigin: ").append(toIndentedString(transactionOrigin)).append("\n");
    sb.append("    creationDate: ").append(toIndentedString(creationDate)).append("\n");
    sb.append("    postedDate: ").append(toIndentedString(postedDate)).append("\n");
    sb.append("    balance: ").append(toIndentedString(balance)).append("\n");
    sb.append("    cardNumber: ").append(toIndentedString(cardNumber)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    references: ").append(toIndentedString(references)).append("\n");
    sb.append("    awardPointsInfo: ").append(toIndentedString(awardPointsInfo)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
